const GET_GIFS_REQUEST = "GET_GIFS_REQUEST";
const GET_GIFS_SUCCESS = "GET_GIFS_SUCCESS";
const GET_GIFS_FAILURE = "GET_GIFS_FAILURE";

const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";

export {
  GET_GIFS_REQUEST,
  GET_GIFS_SUCCESS,
  GET_GIFS_FAILURE,
  GET_CATEGORIES_REQUEST,
  GET_CATEGORIES_SUCCESS,
  GET_CATEGORIES_FAILURE,
  SET_SEARCH_TEXT,
};
